Name,DescriptionRegex,Description  
Regex_poland_eu_mobile_number,"^\+48[0-9]{9}$","Validates Polish mobile phone numbers in international format (+48 followed by 9 digits)"  [oai_citation:0‡github.com](https://github.com/mnestorov/regex-patterns?utm_source=chatgpt.com)  
CEP_AzureEmulatorStorageAccountFilter,"(placeholder)","Filter regex for Azure Emulator Storage Account (internal DLP classification) — excludes emulator accounts"  
CEP_AzureEmulatorStorageAccountFilter,"(placeholder)","Duplicate entry: filter regex for Azure Emulator Storage Account (internal DLP classification)"  
CEP_CommonExampleKeywords,"(placeholder)","Regex for common example keywords (used in DLP to exclude false positives) — internal classification"  
CEP_CommonExampleKeywords,"(placeholder)","Duplicate entry: Regex for common example keywords (internal classification)"  
CEP_PasswordPlaceHolder,"(placeholder)","Regex placeholder for password-like strings (internal classification) — used to detect generic password fields"  
CEP_PasswordPlaceHolder,"(placeholder)","Duplicate entry: Regex placeholder for password-like strings (internal classification)"  
CEP_Regex_AzureConnectionString,"(placeholder)","Regex to detect Azure connection strings (internal classification) — e.g., Azure Storage/Service Bus connection strings"  
CEP_Regex_AzureConnectionString,"(placeholder)","Duplicate entry: Regex to detect Azure connection strings (internal classification)"  
CEP_Regex_AzureDocumentDBAuthKey,"(placeholder)","Regex to detect Azure DocumentDB (Cosmos DB) authorization keys (internal classification)"  
CEP_Regex_AzureDocumentDBAuthKey,"(placeholder)","Duplicate entry: Regex to detect Azure DocumentDB (Cosmos DB) authorization keys (internal classification)"  
CEP_Regex_AzureIoTConnectionString,"(placeholder)","Regex to detect Azure IoT Hub connection strings (internal classification)"  
CEP_Regex_AzureIoTConnectionString,"(placeholder)","Duplicate entry: Regex to detect Azure IoT Hub connection strings (internal classification)"  
CEP_Regex_AzurePublishSettingPasswords,"(placeholder)","Regex to detect Azure publish settings file passwords (internal classification)"  
CEP_Regex_AzurePublishSettingPasswords,"(placeholder)","Duplicate entry: Regex to detect Azure publish settings file passwords (internal classification)"  
Regex_sweden_eu_telephone_number,"^\+46(7[0236]\d{7})$","Validates Swedish mobile phone numbers in international format (+46)"  
Regex_sweden_passport_number,"^\d{8}$","Validates Swedish passport numbers (8 digits)"  
Regex_swift,"^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$","Validates SWIFT/BIC bank codes"  
Regex_taiwan_passport,"^[A-Z]\d{8}$","Validates Taiwan passport numbers (1 letter followed by 8 digits)"  
Regex_taiwan_resident_certificate,"^[A-Za-z]{2}\d{8}$","Validates Taiwan resident certificate numbers (2 letters followed by 8 digits)"  
Regex_uae_id_card_number,"^784-?\d{4}-?\d{7}-?\d$","Validates UAE Emirates ID card numbers"  
Regex_uae_passport_number,"^[A-Z0-9]{9}$","Validates UAE passport numbers (9 alphanumeric characters)"  
Regex_uk_electoral,"^[A-Za-z]{2}\d{1,4}$","Validates UK electoral IDs (2 letters followed by 1-4 digits)"  
Regex_uk_eu_formatted_mobile_number,"^\+44\s?7\d{3}\s?\d{6}$","Validates UK mobile numbers in international format (+44)"  
Regex_uk_eu_formatted_telephone_number,"^\+44\s?(?:1|2)\d{1,3}\s?\d{6,8}$","Validates UK landline numbers in international format (+44)"  
Regex_uk_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates GPS coordinates in decimal degrees format (lat,long)"  
Regex_uk_eu_gps_data_2,"^[NSEW]\s*\d{1,3}\°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}\°\s*\d{1,2}\.\d+'$","Validates GPS coordinates in degrees and minutes with N/S/E/W"  
Regex_uk_eu_mobile_number,"^07\d{9}$","Validates UK mobile numbers (local format starting with 07)"  
Regex_uk_eu_tax_file_number,"^[A-Z]{2}\d{6}[A-Z]$","Validates UK tax file numbers (2 letters, 6 digits, 1 letter)"  
Regex_uk_eu_telephone_number,"^0(?:1|2)\d{8,9}$","Validates UK landline numbers in local format starting with 01 or 02"  
Regex_Ukraine_Passport_Domestic,"^[0-9]{9,10}$","Validates Ukraine domestic passport numbers (9-10 digits)"  
Regex_Ukraine_Passport_International,"^[A-Z0-9]{2}\d{6}$","Validates Ukraine international passport numbers (2 letters/digits followed by 6 digits)"  
Regex_usa_Bank_Account,"^\d{1,17}$","Validates USA bank account numbers (1-17 digits)"  
Regex_usa_bank_account_number,"^\d{1,17}$","Validates USA bank account numbers (1-17 digits)"  
Regex_poland_eu_mobile_number,"^\+48[0-9]{9}$","Validates Polish mobile phone numbers in international format (+48 plus 9 digits)"  
CEP_AzureEmulatorStorageAccountFilter,"(placeholder)","Filter regex for Azure Emulator Storage Account (internal DLP classification) — excludes emulator accounts"  
CEP_AzureEmulatorStorageAccountFilter,"(placeholder)","Duplicate: Filter regex for Azure Emulator Storage Account (internal DLP classification)"  
CEP_CommonExampleKeywords,"(placeholder)","Regex for common ‘example’ keywords to avoid false positives (e.g., contoso, sandbox) in DLP rules"  
CEP_CommonExampleKeywords,"(placeholder)","Duplicate: Regex for common ‘example’ keywords in DLP rules"  
CEP_PasswordPlaceHolder,"^(?:Password|pwd)\s{0,2}=\s{0,2}\*(?:.*)$","Regex detecting placeholder password strings (e.g., `Password = *`) in connection strings or config‑files"  [oai_citation:0‡Microsoft Learn](https://learn.microsoft.com/en-us/purview/sit-defn-sql-server-connection-string?utm_source=chatgpt.com)  
CEP_PasswordPlaceHolder,"^(?:Password|pwd)\s{0,2}=\s{0,2}\*(?:.*)$","Duplicate: Regex detecting placeholder password strings in config or connection strings"  
CEP_Regex_AzureConnectionString,"^.*(?:Server|server|Data Source)=.{1,200}(?:cloudapp\.azure\.com|cloudapp\.azure\.net|database\.windows\.net).{1,300}(?:Password|password|pwd)=[^;\"']+.*$","Regex to detect Azure connection strings with server endpoint and password fields.  [oai_citation:1‡Microsoft Learn](https://learn.microsoft.com/en-us/purview/sit-defn-azure-iaas-database-connection-string-azure-sql-connection-string?utm_source=chatgpt.com)"  
CEP_Regex_AzureConnectionString,"^.*(?:Server|server|Data Source)=.{1,200}(?:cloudapp\.azure\.com|cloudapp\.azure\.net|database\.windows\.net).{1,300}(?:Password|password|pwd)=[^;\"']+.*$","Duplicate: Regex to detect Azure connection strings"  
CEP_Regex_AzureDocumentDBAuthKey,"(placeholder)","Regex to detect Azure DocumentDB (Cosmos DB) authorization keys (internal classification)"  
CEP_Regex_AzureDocumentDBAuthKey,"(placeholder)","Duplicate: Regex to detect Azure DocumentDB (Cosmos DB) authorization keys"  
CEP_Regex_AzureIoTConnectionString,"^HostName=[^;]+\.azure-devices\.net;SharedAccessKeyName=[^;]+;SharedAccessKey=[A-Za-z0-9\/\+]+=;$","Regex to detect Azure IoT Hub connection strings (HostName=…;SharedAccessKeyName=…;SharedAccessKey=…)  [oai_citation:2‡Microsoft Learn](https://learn.microsoft.com/en-us/purview/sit-defn-azure-iot-connection-string?utm_source=chatgpt.com)"  
CEP_Regex_AzureIoTConnectionString,"^HostName=[^;]+\.azure-devices\.net;SharedAccessKeyName=[^;]+;SharedAccessKey=[A-Za-z0-9\/\+]+=;$","Duplicate: Regex to detect Azure IoT Hub connection strings"  
CEP_Regex_AzurePublishSettingPasswords,"(placeholder)","Regex to detect password fields in Azure publish settings files (internal classification)"  
CEP_Regex_AzurePublishSettingPasswords,"(placeholder)","Duplicate: Regex to detect password fields in Azure publish settings files"  
Regex_south_korea_passport_number,"^[A-PR-WYa-pr-wy][0-9]{8}$","Validates South Korean passport numbers (1 letter excluding Q, X, Z then 8 digits)"  
Regex_spain_eu_formatted_mobile_number,"^\+34\s?[6-7][0-9]\s?[0-9]{3}\s?[0-9]{3}$","Validates Spain mobile numbers in international format (+34) beginning 6 or 7"  
Regex_spain_eu_formatted_telephone_number,"^\+34\s?(?:8|9)[0-9]\s?[0-9]{3}\s?[0-9]{3}$","Validates Spain landline numbers in international format (+34) starting 8 or 9"  
Regex_spain_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Spain/Europe GPS coordinates in decimal degrees format (lat,long)"  
Regex_spain_eu_gps_data_2,"^[NSEW]\s*\d{1,3}\°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}\°\s*\d{1,2}\.\d+'$","Validates Spain/Europe GPS coordinates in degrees and minutes with N/S/E/W"  
Regex_spain_eu_mobile_number,"^\+34[6-7][0-9]{8}$","Validates Spain mobile numbers in international format +34 then 9 digits starting 6 or 7"  
Regex_spain_eu_national_id_card,"^[0-9]{8}[A-Z]$","Validates Spain national ID card numbers (DNI) 8 digits and a letter"  
Regex_spain_eu_passport_date,"^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/\d{4}$","Validates Spain passport date (DD/MM/YYYY) format"  
Regex_spain_eu_passport_number,"^[A-Z0-9]{1,7}$","Validates Spain passport numbers (up to 7 alphanumeric characters)"  
Regex_spain_eu_ssn_or_equivalent,"^[0-9]{8}[A-Z]$","Validates Spain SSN or equivalent (same as DNI format: 8 digits + letter)"  
Regex_spain_eu_tax_file_number,"^ES[0-9]{8}[A-Z]$","Validates Spain tax file number (NIF) starting 'ES', 8 digits then a letter"  
Regex_spain_eu_telephone_number,"^\+34[89][0-9]{8}$","Validates Spain landline numbers in international format +34 then 9 digits starting 8 or 9"  
Regex_sweden_eu_driver's_license_number,"^[A-Z]{2}\d{6}$","Validates Sweden driver’s licence numbers: 2 letters + 6 digits"  
Regex_sweden_eu_formatted_mobile_number,"^\+46\s?7[0236]\s?\d{1}\s?\d{3}\s?\d{3}$","Validates Sweden mobile numbers in international format +46, prefix 7, etc."  
Regex_sweden_eu_formatted_telephone_number,"^\+46\s?[1-468]\s?\d{1}\s?\d{3}\s?\d{3}$","Validates Sweden landline numbers in international format +46"  
Regex_sweden_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Sweden/Europe GPS coordinates in decimal degrees (lat,long)"  
Regex_sweden_eu_gps_data_2,"^[NSEW]\s*\d{1,3}\°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}\°\s*\d{1,2}\.\d+'$","Validates Sweden/Europe GPS coordinates in degrees/minutes with N/S/E/W"  
Regex_sweden_eu_mobile_number,"^\+467[0-9]{7}$","Validates Sweden mobile numbers in international format +46, then 7 and 7 digits"  
Regex_sweden_eu_passport_date,"^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[012])-\d{4}$","Validates Sweden passport date in DD‑MM‑YYYY format"  
Regex_sweden_eu_ssn_or_equivalent,"^\d{6}[- ]?\d{4}$","Validates Sweden social security number format (6 digits, optional hyphen/space, 4 digits)"  
Regex_sweden_eu_tax_file_number,"^SE\d{12}$","Validates Sweden tax file number (VAT) starting SE then 12 digits"  
Regex_sweden_eu_telephone_number,"^\+46[1-8][0-9]{7,8}$","Validates Sweden telephone numbers in international format +46”  
Regex_sweden_passport_number,"^\d{8}$","Validates Sweden passport number (8 digits)"  
Regex_swift,"^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$","Validates SWIFT/BIC bank codes"  
Regex_taiwan_passport,"^[A-Z]\d{8}$","Validates Taiwan passport numbers (1 letter + 8 digits)"  
Regex_taiwan_resident_certificate,"^[A-Za-z]{2}\d{8}$","Validates Taiwan resident certificate numbers (2 letters + 8 digits)"  
Regex_uae_id_card_number,"^784-?\d{4}-?\d{7}-?\d$","Validates UAE Emirates ID card numbers format"  
Regex_uae_passport_number,"^[A-Z0-9]{9}$","Validates UAE passport numbers (9 alphanumeric chars)"  
Regex_uk_electoral,"^[A-Za-z]{2}\d{1,4}$","Validates UK electoral ID codes (2 letters then 1‑4 digits)"  
Regex_uk_eu_formatted_mobile_number,"^\+44\s?7\d{3}\s?\d{6}$","Validates UK mobile numbers in international format +44"  
Regex_uk_eu_formatted_telephone_number,"^\+44\s?(?:1|2)\d{1,3}\s?\d{6,8}$","Validates UK landline numbers in international format +44"  
Regex_uk_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates UK/Europe GPS coordinates in decimal degrees (lat,long)"  
Regex_uk_eu_gps_data_2,"^[NSEW]\s*\d{1,3}\°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}\°\s*\d{1,2}\.\d+'$","Validates UK/Europe GPS coordinates in degrees/minutes with N/S/E/W"  
Regex_uk_eu_mobile_number,"^07\d{9}$","Validates UK mobile numbers local format starting 07 then 9 digits"  
Regex_uk_eu_tax_file_number,"^[A-Z]{2}\d{6}[A-Z]$","Validates UK tax file number (2 letters, 6 digits, 1 letter)"  
Regex_uk_eu_telephone_number,"^0(?:1|2)\d{8,9}$","Validates UK telephone numbers local format starting 01 or 02"  
Regex_Ukraine_Passport_Domestic,"^[0-9]{9,10}$","Validates Ukraine domestic passport numbers (9‑10 digits)"  
Regex_Ukraine_Passport_International,"^[A-Z0-9]{2}\d{6}$","Validates Ukraine international passport numbers (2 alphanumeric then 6 digits)"  
Regex_usa_Bank_Account,"^\d{1,17}$","Validates USA bank account numbers (1‑17 digits)"  
Regex_usa_bank_account_number,"^\d{1,17}$","Validates USA bank account numbers (1‑17 digits)"  
Regex_romania_eu_driver's_license_number,"(placeholder)","Validates Romanian driver’s licence numbers"  
Regex_romania_eu_formatted_mobile_number,"^\+40[1-9][0-9]{8,9}$","Validates Romanian mobile numbers in international format (+40) then 8‑9 digits"    
Regex_romania_eu_formatted_telephone_number,"^\+40[1-9][0-9]{8,9}$","Validates Romanian landline numbers in international format (+40) then 8‑9 digits"  
Regex_romania_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates GPS coords in decimal degrees (latitude, longitude) for Romania/Europe"    
Regex_romania_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates GPS coords in degrees and minutes with N/S/E/W for Romania/Europe"    
Regex_romania_eu_mobile_number,"^\+40[7][0-9]{8}$","Validates Romanian mobile numbers in international format +40 then 9 digits starting 7"    
Regex_romania_eu_national_id_card,"^[1-9]\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])(0[1-9]|[1-4]\d|5[0-2]|99)(00[1-9]|0[1-9]\d|[1-9]\d\d)\d$","Validates Romanian national ID (CNP) format (sex+birthdate+…), as example pattern found.  [oai_citation:0‡regex101](https://regex101.com/library/bpaE5K?utm_source=chatgpt.com)"    
Regex_romania_eu_passport_date,"^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/\d{4}$","Validates Romanian passport date in DD/MM/YYYY format"    
Regex_romania_eu_passport_number,"^[A-Z]{2}\d{6}$","Validates Romanian passport number (2 letters + 6 digits) (approximate)"    
Regex_romania_eu_tax_file_number,"^RO\d{2,10}$","Validates Romanian tax/VAT file number (starts RO, 2‑10 digits)  [oai_citation:1‡GitHub](https://github.com/mnestorov/regex-patterns?utm_source=chatgpt.com)"    
Regex_romania_eu_telephone_number,"^\+40[1-9][0-9]{8,9}$","Validates Romanian telephone numbers in international format +40 then 8‑9 digits"    
Regex_Russian_Passport_Number_Domestic,"^\d{10}$","Validates Russia domestic passport number (10 digits) (approximate)"    
Regex_Russian_Passport_Number_International,"^[A-Z]{2}\d{7}$","Validates Russia international passport number (2 letters + 7 digits) (approximate)"    
Regex_saudi_arabia_national_id,"^\d{10}$","Validates Saudi Arabia national ID (10 digits) (approximate)"    
Regex_Scanner_JsonWebToken_JwtToken_51810644_CEP2.0,"^eyJ[A-Za-z0-9\-_]+\.[A-Za-z0-9\-_]+\.(?:[A-Za-z0-9\-_]+)$","Detects JSON Web Token (JWT) format starting with “eyJ…” (common JWT prefix)"    
Regex_Scanner_LoginCredentials_Login_2383799_CEP2.0,"(placeholder)","Detects login credential strings in code contexts (internal classification)"    
Regex_Scanner_PasswordContextInCode_Password_62074597_CEP2.0,"(placeholder)","Detects password contexts in source code (internal classification)"    
Regex_Scanner_SymmetricKey128_SymmetricKey_61027830_CEP2.0,"^(?:[A-Za-z0-9\+\/]{22}==)$","Detects 128‑bit symmetric key Base64 string (approximate)"    
Regex_Scanner_SymmetricKey360_SymmetricKey_31201899_CEP2.0,"^(?:[A-Za-z0-9\+\/]{48}==)$","Detects 360‑bit symmetric key Base64 string (approximate)"    
Regex_singapore_driving_license,"^[A-Z]\d{7}[A-Z]$","Validates Singapore driving licence number (1 letter + 7 digits + letter) (approximate)"    
Regex_singapore_nric,"^[SFTG]\d{7}[A-Z]$","Validates Singapore NRIC / FIN numbers: starts S, T, F or G + 7 digits + letter.  [oai_citation:2‡Stack Overflow](https://stackoverflow.com/questions/29743154/regular-expression-for-nric-fin-in-singapore?utm_source=chatgpt.com)"    
Regex_singapore_passport_number,"^[A-Z]\d{7}[A-Z0-9]$","Validates Singapore passport numbers (1 letter + 7 digits + alphanumeric) (approximate)  [oai_citation:3‡Microsoft Learn](https://learn.microsoft.com/en-us/purview/sit-defn-singapore-passport-number?utm_source=chatgpt.com)"    
Regex_slovakia_eu_driver's_license_number,"(placeholder)","Validates Slovakia driver’s licence number (approximate)"    
Regex_slovakia_eu_formatted_mobile_number,"^\+421[9][0-9]{8}$","Validates Slovak mobile numbers in international format +421 then 9 digits starting 9 (approximate)  [oai_citation:4‡GitHub](https://github.com/mnestorov/regex-patterns?utm_source=chatgpt.com)"    
Regex_slovakia_eu_formatted_telephone_number,"^\+421(?:2|3|4)[0-9]{7}$","Validates Slovak landline numbers in international format +421 then 8 digits (approximate)"    
Regex_slovakia_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates GPS coords in decimal degrees for Slovakia/Europe"    
Regex_slovakia_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates GPS coords degrees & minutes with N/S/E/W for Slovakia/Europe"    
Regex_slovakia_eu_mobile_number,"^\+4219[0-9]{8}$","Validates Slovak mobile numbers in international format +421 then 9 digits starting 9 (approximate)"    
Regex_slovakia_eu_national_id_card,"^\d{10}$","Validates Slovak national ID card number (10 digits) (approximate)"    
Regex_slovakia_eu_passport_number,"^[A-Z0-9]{8}$","Validates Slovak passport number (alphanumeric, 8 chars) (approximate)"    
Regex_slovakia_eu_tax_file_number,"^SK\d{10}$","Validates Slovak tax file number (VAT) starting SK followed by 10 digits (approximate)  [oai_citation:5‡GitHub](https://github.com/mnestorov/regex-patterns?utm_source=chatgpt.com)"    
Regex_slovakia_eu_telephone_number,"^0(?:2|3|4|5)\d{7}$","Validates Slovak telephone numbers local format starting 02/03/04/05 then 7 digits (approximate)"    
Regex_slovenia_eu_driver's_license_number,"(placeholder)","Validates Slovenia driver’s licence number (approximate)"    
Regex_slovenia_eu_formatted_mobile_number,"^\+386[1-9][0-9]{6,7}$","Validates Slovenian mobile numbers in international format +386 then 7‑8 digits (approximate)  [oai_citation:6‡GitHub](https://github.com/mnestorov/regex-patterns?utm_source=chatgpt.com)"    
Regex_slovenia_eu_formatted_telephone_number,"^\+386[1-9][0-9]{6,7}$","Validates Slovenian landline numbers in international format +386 then 7‑8 digits (approximate)"    
Regex_slovenia_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates GPS coords in decimal degrees for Slovenia/Europe"    
Regex_slovenia_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates GPS coords degrees & minutes with N/S/E/W for Slovenia/Europe"    
Regex_slovenia_eu_mobile_number,"^\+386[1-9][0-9]{6,7}$","Validates Slovenian mobile numbers in international format +386 then 7‑8 digits (approximate)"    
Regex_slovenia_eu_national_id_card,"^\d{7,9}$","Validates Slovenian national ID card number (7‑9 digits) (approximate)"    
Regex_slovenia_eu_passport_number,"^[A-Z0-9]{8}$","Validates Slovenian passport number (alphanumeric, 8 chars) (approximate)"    
Regex_slovenia_eu_tax_file_number,"^SI\d{8}$","Validates Slovenian tax file number (VAT) starting SI + 8 digits (approximate)  [oai_citation:7‡GitHub](https://github.com/mnestorov/regex-patterns?utm_source=chatgpt.com)"    
Regex_slovenia_eu_telephone_number,"^0[1-9]\d{6,7}$","Validates Slovenian telephone numbers local format starting 0 then 7‑8 digits (approximate)"    
Regex_south_korea_driver's_license_10digits,"^\d{10}$","Validates South Korean driver’s licence number (10 digits) (approximate)"    
Regex_south_korea_driver's_license_12digits,"^\d{12}$","Validates South Korean driver’s licence number (12 digits) (approximate)"  
Regex_lithuania_eu_driver's_license_number,"(placeholder)","Validates Lithuania driver’s licence numbers (approximate)"  
Regex_lithuania_eu_formatted_mobile_number,"^\+3706\d{7}$","Validates Lithuania mobile numbers in international format +370 then 8 digits starting 6"  
Regex_lithuania_eu_formatted_telephone_number,"^\+370[1-5]\d{7}$","Validates Lithuania landline numbers in international format +370 then 8 digits starting 1‑5"  
Regex_lithuania_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Lithuania/Europe GPS coordinates in decimal degrees (lat,long)"  
Regex_netherlands_eu_telephone_number,"^\+31[1-9]\d{8}$","Validates Netherlands telephone numbers in international format +31 then 9 digits"  
Regex_philippines_passport_number,"^[A-Z]\d{7}$","Validates Philippines passport numbers (1 letter + 7 digits)"  
Regex_philippines_unified_id,"^\d{12}$","Validates Philippines Unified Multi-Purpose ID (UMID) 12 digits"  
Regex_phillipines_national_id,"^\d{12}$","Validates Philippines National ID 12 digits (approximate)"  
Regex_poland_eu_driver's_license_number,"(placeholder)","Validates Poland driver’s licence numbers"  
Regex_poland_eu_formatted_mobile_number,"^\+48[5-8]\d{7}$","Validates Poland mobile numbers in international format +48 then 9 digits starting 5‑8"  
Regex_poland_eu_formatted_telephone_number,"^\+48[1-4]\d{7}$","Validates Poland landline numbers in international format +48 then 8 digits starting 1‑4"  
Regex_poland_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Poland/Europe GPS coordinates in decimal degrees (lat,long)"  
Regex_poland_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Poland/Europe GPS coordinates in degrees/minutes with N/S/E/W"  
Regex_poland_eu_mobile_number,"^\+48[5-8]\d{7}$","Validates Poland mobile numbers +48 followed by 9 digits starting 5‑8"  
Regex_poland_eu_tax_file_number,"^\d{10}$","Validates Poland tax file number (NIP) 10 digits"  
Regex_poland_eu_telephone_number,"^\+48[1-4]\d{7}$","Validates Poland landline numbers +48 then 8 digits starting 1‑4"  
Regex_portugal_citizen_card,"^\d{8}[A-Z]{2}$","Validates Portugal citizen card number: 8 digits + 2 letters"  
Regex_portugal_eu_driver's_license_number,"^\d{9}$","Validates Portugal driver’s licence numbers 9 digits"  
Regex_portugal_eu_formatted_mobile_number,"^\+3519\d{8}$","Validates Portugal mobile numbers +351 then 9 digits starting 9"  
Regex_portugal_eu_formatted_telephone_number,"^\+3512\d{7}$","Validates Portugal landline numbers +351 then 8 digits starting 2"  
Regex_portugal_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Portugal/Europe GPS coordinates in decimal degrees (lat,long)"  
Regex_portugal_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Portugal/Europe GPS coordinates degrees/minutes with N/S/E/W"  
Regex_portugal_eu_mobile_number,"^\+3519\d{8}$","Validates Portugal mobile numbers +351 then 9 digits starting 9"  
Regex_portugal_eu_passport_number,"^[A-Z0-9]{8}$","Validates Portugal passport numbers 8 alphanumeric characters"  
Regex_portugal_eu_tax_file_number,"^\d{9}$","Validates Portugal tax file number (NIF) 9 digits"  
Regex_portugal_eu_telephone_number,"^\+3512\d{7}$","Validates Portugal landline numbers +351 then 8 digits starting 2"  
Regex_qatari_id_card,"^\d{11}$","Validates Qatari ID card numbers (11 digits)"  
Regex_Ranker_CSCAN-AZURE0020_0eae114f-baad-4dba-a100-c5b34d217964_60068066_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0020_ServerName_21454193_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0020_UserName_58870012_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0030_9beb734f-ba2b-452b-b422-589f5ac467ef_43332040_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0030_dcd6d403-fe3c-4807-bfd8-ae6486752696_54444047_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0030_HostName_34640832_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0030_Partial_501d2bf7-e635-4014-a9e8-eb68bae2aef1_20234383_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0040_FiledName_47891719_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0040_HostName_28372289_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0050_HostName_13869071_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0050_KeyName_57712780_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0050_Partial_8305ad49-df2a-4e1e-a008-fc63cb1db966_49652976_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0060_Code_f0227d5e-f4ab-4617-b396-f0250e331e69_26753075_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0060_HighRiskResource_ResourceType_26753075_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0061_ResourceType_64554036_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0070_combined_ranker_CEP2.0_17ba94a9-a24c-4c84-a838-22a1c0c192e7_26987408_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0070_combined_ranker_CEP2.0_AccountKey_41560081_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0070_combined_ranker_CEP2.0_AccountName_40041277_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0070_combined_ranker_CEP2.0_d37929c5-be80-4f59-951f-5dc6f21d8892_17911681_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0070_combined_ranker_CEP2.0_Endpoint_24827179_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0070_combined_ranker_CEP2.0_EndpointSuffix_22118023_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0070_combined_ranker_CEP2.0_EndpointSuffix_64844482_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0080_AccountEndpoint_38496415_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0080_Partial_1eb5757c-210e-46a5-876e-b0ad231103e9_10923418_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0090_b08f98f2-d980-4598-814b-67c29887ebff_33624151_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0130_AzureBatch_a5d6121e-e9af-4b7d-a7da-9aad47e4c66d_53046711_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0130_Prefix_a853ad91-d200-41b2-8dc4-4ce41dda3b81_3056034_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-AZURE0140_RefreshToken_74aa94f2-34ed-40bf-ba88-0bc17398a9cf_9381496_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_Ranker_CSCAN-GENERAL0030_combined_ranker_CEP2.0_ServerName_53517805_CEP2.0,"(placeholder)","Internal Microsoft Purview Ranker regex – not publicly documented"  
Regex_hungary_eu_tax_file_number,"^\d{8}$","Validates Hungary tax file number (8 digits, NIP/Nemzeti Adószám)"  
Regex_hungary_eu_telephone_number,"^\+36[1-9]\d{6,7}$","Validates Hungary landline/mobile numbers in international format +36 followed by 7-8 digits"  
Regex_india_driving_license,"^[A-Z]{2}\d{2}\s?\d{11}$","Validates India driving licence: state code + 2 digits + 11 numeric characters"  
Regex_india_permanent_account_number,"^[A-Z]{5}\d{4}[A-Z]{1}$","Validates India PAN (Permanent Account Number): 5 letters, 4 digits, 1 letter"  
Regex_india_voter_id_card,"^[A-Z]{3}\d{7}$","Validates India Voter ID (EPIC) number: 3 letters + 7 digits"  
Regex_indonesia_drivers_license_number,"^\d{12,16}$","Validates Indonesia driving licence numbers (12-16 digits)"  
Regex_indonesia_id_card,"^\d{16}$","Validates Indonesia national ID (KTP) 16 digits"  
Regex_indonesia_passport_number,"^[A-Z]{1}\d{7}$","Validates Indonesia passport number (1 letter + 7 digits)"  
Regex_ipv4_address,"^(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)){3}$","Validates IPv4 addresses"  
Regex_ipv6_address,"^([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$","Validates IPv6 addresses"  
Regex_ireland_eu_driver's_license_number,"(placeholder)","Validates Ireland driver’s licence numbers"  
Regex_ireland_eu_formatted_mobile_number,"^\+3538\d{7,8}$","Validates Ireland mobile numbers in international format +353 then 7-8 digits"  
Regex_ireland_eu_formatted_telephone_number,"^\+353[1-9]\d{7,8}$","Validates Ireland landline numbers +353 then 7-8 digits"  
Regex_ireland_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Ireland/Europe GPS coordinates in decimal degrees"  
Regex_ireland_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Ireland GPS coordinates degrees/minutes N/S/E/W"  
Regex_ireland_eu_mobile_number,"^\+3538\d{7,8}$","Validates Ireland mobile numbers in international format"  
Regex_ireland_eu_national_id_card,"(placeholder)","Validates Ireland national ID card (approximate)"  
Regex_ireland_eu_passport_date,"^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/\d{4}$","Validates Ireland passport date DD/MM/YYYY"  
Regex_ireland_eu_passport_number,"^[A-Z0-9]{8}$","Validates Ireland passport number 8 alphanumeric characters"  
Regex_ireland_eu_tax_file_number,"^\d{7}[A-Z]{1}$","Validates Ireland tax file number (7 digits + 1 letter)"  
Regex_ireland_eu_telephone_number,"^\+353[1-9]\d{7,8}$","Validates Ireland landline number in international format"  
Regex_israel_bank_account_number,"^\d{9,12}$","Validates Israel bank account number (9-12 digits)"  
Regex_italy_drivers_license_number,"^[A-Z]{2}\d{11}$","Validates Italy driver’s licence (2 letters + 11 digits)"  
Regex_italy_eu_formatted_mobile_number,"^\+39[3]\d{8}$","Validates Italy mobile numbers +39 then 9 digits starting 3"  
Regex_italy_eu_formatted_telephone_number,"^\+39[0-9]{8,10}$","Validates Italy landline numbers in international format +39 then 8-10 digits"  
Regex_italy_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Italy/Europe GPS coordinates in decimal degrees"  
Regex_italy_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Italy GPS coordinates degrees/minutes N/S/E/W"  
Regex_italy_eu_mobile_number,"^\+39[3]\d{8}$","Validates Italy mobile numbers +39 then 9 digits starting 3"  
Regex_italy_eu_national_id_card,"^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$","Validates Italy national ID (Codice Fiscale) format"  
Regex_italy_eu_passport_date,"^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/\d{4}$","Validates Italy passport date DD/MM/YYYY"  
Regex_italy_eu_passport_number,"^[A-Z0-9]{8}$","Validates Italy passport number 8 alphanumeric characters"  
Regex_italy_eu_tax_file_number,"^[0-9]{11}$","Validates Italy tax file number (Codice Fiscale digits) 11 digits"  
Regex_italy_eu_telephone_number,"^\+39[0-9]{8,10}$","Validates Italy landline numbers +39 then 8-10 digits"  
Regex_jp_residence_card_number,"^[A-Z]{2}\d{7}$","Validates Japan residence card numbers (2 letters + 7 digits)"  
Regex_latvia_eu_driver's_license_number,"(placeholder)","Validates Latvia driver’s licence numbers"  
Regex_latvia_eu_formatted_mobile_number,"^\+371[2-9]\d{6}$","Validates Latvia mobile numbers +371 then 7 digits starting 2-9"  
Regex_latvia_eu_formatted_telephone_number,"^\+371[1-9]\d{5,6}$","Validates Latvia landline numbers +371 then 6-7 digits"  
Regex_latvia_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Latvia/Europe GPS coordinates in decimal degrees"  
Regex_latvia_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Latvia GPS coordinates degrees/minutes N/S/E/W"  
Regex_latvia_eu_mobile_number,"^\+371[2-9]\d{6}$","Validates Latvia mobile numbers +371 then 7 digits starting 2-9"  
Regex_latvia_eu_national_id_card,"^\d{11}$","Validates Latvia national ID (11 digits, approximate)"  
Regex_latvia_eu_national_id_card_new_format,"^[A-Z]{1}\d{6}-\d{5}$","Validates Latvia new format national ID: 1 letter + 6 digits - 5 digits"  
Regex_latvia_eu_passport_number,"^[A-Z0-9]{8}$","Validates Latvia passport number 8 alphanumeric characters"  
Regex_latvia_eu_tax_file_number,"^\d{11}$","Validates Latvia tax file number (11 digits, approximate)"  
Regex_latvia_eu_telephone_number,"^\+371[1-9]\d{5,6}$","Validates Latvia landline numbers +371 then 6-7 digits"  
Regex_dummy_no_match_number,"^$","Dummy regex that does not match anything"  
Regex_Ecuador_Unique_Identification_Number,"^\d{10}$","Validates Ecuador Unique Identification Number (cédula) 10 digits"  
Regex_estonia_eu_driver's_license_number,"(placeholder)","Validates Estonia driver’s licence numbers"  
Regex_estonia_eu_formatted_mobile_number,"^\+372[5-6]\d{6}$","Validates Estonia mobile numbers +372 then 7 digits starting 5 or 6"  
Regex_estonia_eu_formatted_telephone_number,"^\+372[3-4]\d{5}$","Validates Estonia landline numbers +372 then 6 digits starting 3 or 4"  
Regex_estonia_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Estonia GPS coordinates in decimal degrees"  
Regex_estonia_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Estonia GPS coordinates degrees/minutes N/S/E/W"  
Regex_estonia_eu_mobile_number,"^\+372[5-6]\d{6}$","Validates Estonia mobile numbers +372 then 7 digits starting 5 or 6"  
Regex_estonia_eu_national_id_card,"^\d{11}$","Validates Estonia national ID (11 digits)"  
Regex_estonia_eu_passport_number,"^[A-Z]{2}\d{7}$","Validates Estonia passport number: 2 letters + 7 digits"  
Regex_estonia_eu_tax_file_number,"^\d{11}$","Validates Estonia tax file number (11 digits)"  
Regex_estonia_eu_telephone_number,"^\+372[3-4]\d{5}$","Validates Estonia landline numbers +372 then 6 digits starting 3 or 4"  
Regex_eu_passport_date1,"^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/\d{4}$","Validates EU passport date DD/MM/YYYY"  
Regex_eu_passport_date2,"^\d{4}-\d{2}-\d{2}$","Validates EU passport date YYYY-MM-DD"  
Regex_eu_passport_date3,"^\d{2}-\d{2}-\d{4}$","Validates EU passport date DD-MM-YYYY"  
Regex_Filter_TrivialValue2_20601768_CEP2.0,"(placeholder)","Internal Microsoft Purview DLP regex – trivial value filter"  
Regex_finland_eu_driver's_license_number,"(placeholder)","Validates Finland driver’s licence numbers"  
Regex_finland_eu_formatted_mobile_number,"^\+3584\d{7,8}$","Validates Finland mobile numbers +3584 then 7-8 digits"  
Regex_finland_eu_formatted_telephone_number,"^\+358[1-3]\d{6,7}$","Validates Finland landline numbers +358 then 7-8 digits starting 1-3"  
Regex_finland_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Finland GPS coordinates in decimal degrees"  
Regex_finland_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Finland GPS coordinates degrees/minutes N/S/E/W"  
Regex_finland_eu_mobile_number,"^\+3584\d{7,8}$","Validates Finland mobile numbers +3584 then 7-8 digits"  
Regex_finland_eu_ssn_or_equivalent,"^\d{6}[-+A]\d{3}[0-9A-Z]$","Validates Finland SSN (HETU) format: DDMMYY[-+A]XXXC"  
Regex_finland_eu_tax_file_number,"^\d{11}$","Validates Finland tax file number (11 digits)"  
Regex_finland_eu_telephone_number,"^\+358[1-3]\d{6,7}$","Validates Finland landline numbers +358 then 7-8 digits starting 1-3"  
Regex_Finland_European_Health_Insurance_Number,"^[A-Z]{2}\d{6,9}$","Validates Finland European Health Insurance Number (EHIC) format"  
Regex_finland_passport_number,"^[A-Z]{2}\d{7}$","Validates Finland passport number: 2 letters + 7 digits"  
Regex_france_cni,"^\d{12}$","Validates France National Identity Card (CNI) 12 digits"  
Regex_france_eu_formatted_mobile_number,"^\+33[6-7]\d{8}$","Validates France mobile numbers +33 then 9 digits starting 6 or 7"  
Regex_france_eu_formatted_telephone_number,"^\+33[1-5]\d{8}$","Validates France landline numbers +33 then 9 digits starting 1-5"  
Regex_france_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates France GPS coordinates decimal degrees"  
Regex_france_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates France GPS coordinates degrees/minutes N/S/E/W"  
Regex_france_eu_mobile_number,"^\+33[6-7]\d{8}$","Validates France mobile numbers +33 then 9 digits starting 6 or 7"  
Regex_france_eu_tax_file_number,"^\d{13}$","Validates France tax file number (13 digits, NIF/INSEE)"  
Regex_france_eu_telephone_number,"^\+33[1-5]\d{8}$","Validates France landline numbers +33 then 9 digits starting 1-5"  
Regex_France_Health_Insurance_Number,"^[A-Z]{1}\d{13}$","Validates France Health Insurance Number (INSEE) format"  
Regex_germany_eu_formatted_mobile_number,"^\+49[1-9]\d{9,10}$","Validates Germany mobile numbers +49 then 10-11 digits"  
Regex_germany_eu_formatted_telephone_number,"^\+49[1-9]\d{7,9}$","Validates Germany landline numbers +49 then 8-10 digits"  
Regex_germany_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Germany GPS coordinates decimal degrees"  
Regex_germany_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Germany GPS coordinates degrees/minutes N/S/E/W"  
Regex_germany_eu_mobile_number,"^\+49[1-9]\d{9,10}$","Validates Germany mobile numbers +49 then 10-11 digits"  
Regex_germany_eu_tax_file_number,"^\d{11}$","Validates Germany tax file number (11 digits)"  
Regex_germany_eu_telephone_number,"^\+49[1-9]\d{7,9}$","Validates Germany landline numbers +49 then 8-10 digits"  
Regex_germany_id_card,"^[A-Z0-9]{9}$","Validates Germany ID card (Personalausweis) 9 alphanumeric characters"  
Regex_greece_eu_driver's_license_number,"(placeholder)","Validates Greece driver’s licence numbers"  
Regex_greece_eu_formatted_mobile_number,"^\+30(69\d{8})$","Validates Greece mobile numbers +30 then 9 digits starting 69"  
Regex_greece_eu_formatted_telephone_number,"^\+30(2\d{8})$","Validates Greece landline numbers +30 then 9 digits starting 2"  
Regex_greece_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Greece GPS coordinates decimal degrees"  
Regex_greece_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Greece GPS coordinates degrees/minutes N/S/E/W"  
Regex_greece_eu_mobile_number,"^\+30(69\d{8})$","Validates Greece mobile numbers +30 then 9 digits starting 69"  
Regex_greece_eu_passport_date,"^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/\d{4}$","Validates Greece passport date DD/MM/YYYY"  
Regex_greece_eu_passport_number,"^[A-Z]{1}\d{7}$","Validates Greece passport number 1 letter + 7 digits"  
Regex_greece_eu_tax_file_number,"^\d{9}$","Validates Greece tax file number (9 digits, AFM)"  
Regex_greece_eu_telephone_number,"^\+30(2\d{8})$","Validates Greece landline numbers +30 then 9 digits starting 2"  
Regex_greece_id_card,"^[A-Z0-9]{9}$","Validates Greece ID card 9 alphanumeric characters"  
Regex_hungary_eu_driver's_license_number,"(placeholder)","Validates Hungary driver’s licence numbers"  
Regex_hungary_eu_formatted_mobile_number,"^\+36[20-70]\d{7}$","Validates Hungary mobile numbers +36 then 9 digits"  
Regex_hungary_eu_formatted_telephone_number,"^\+36[1-9]\d{6,7}$","Validates Hungary landline numbers +36 then 7-8 digits"  
Regex_hungary_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Hungary GPS coordinates decimal degrees"  
Regex_hungary_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Hungary GPS coordinates degrees/minutes N/S/E/W"  
Regex_hungary_eu_mobile_number,"^\+36[20-70]\d{7}$","Validates Hungary mobile numbers +36 then 9 digits"  
Regex_hungary_eu_national_id_card,"^\d{8}$","Validates Hungary national ID 8 digits"  
Regex_hungary_eu_passport_date,"^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/\d{4}$","Validates Hungary passport date DD/MM/YYYY"  
Regex_hungary_eu_passport_number,"^[A-Z]{1}\d{7}$","Validates Hungary passport number 1 letter + 7 digits"  
Regex_hungary_eu_ssn_or_equivalent,"^\d{11}$","Validates Hungary social security number or equivalent (11 digits)"  
Regex_bulgaria_eu_formatted_telephone_number,"^\+359[2-9]\d{7}$","Validates Bulgaria landline numbers +359 then 8 digits starting 2-9"  
Regex_bulgaria_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Bulgaria GPS coordinates decimal degrees"  
Regex_bulgaria_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Bulgaria GPS coordinates degrees/minutes N/S/E/W"  
Regex_bulgaria_eu_mobile_number,"^\+3598\d{7}$","Validates Bulgaria mobile numbers +359 then 8 digits starting 8"  
Regex_bulgaria_eu_national_id_card,"^\d{10}$","Validates Bulgaria national ID (10 digits)"  
Regex_bulgaria_eu_passport_number,"^[A-Z]{2}\d{7}$","Validates Bulgaria passport number: 2 letters + 7 digits"  
Regex_bulgaria_eu_tax_file_number,"^\d{9}$","Validates Bulgaria tax file number (9 digits)"  
Regex_bulgaria_eu_telephone_number,"^\+359[2-9]\d{7}$","Validates Bulgaria landline numbers +359 then 8 digits"  
Regex_canada_bank_account_number,"^\d{7,12}$","Validates Canada bank account numbers (7-12 digits)"  
Regex_canada_bank_account_transit_number,"^\d{5}-\d{3}$","Validates Canada bank transit numbers (5 digits branch - 3 digits institution)"  
Regex_canada_health_service_number,"^\d{10}$","Validates Canadian Health Service Number (10 digits)"  
Regex_canada_passport_number,"^[A-Z]\d{7}$","Validates Canada passport number: 1 letter + 7 digits"  
Regex_canada_phin,"^\d{9}$","Validates Canada Personal Health Identification Number (PHIN) 9 digits"  
Regex_colombia_national_id_number,"^\d{10}$","Validates Colombia national ID (Cédula de ciudadanía) 10 digits"  
Regex_croatia_eu_driver's_license_number,"(placeholder)","Validates Croatia driver’s licence numbers"  
Regex_croatia_eu_formatted_mobile_number,"^\+3859\d{7}$","Validates Croatia mobile numbers +385 then 8 digits starting 9"  
Regex_croatia_eu_formatted_telephone_number,"^\+385[1-5]\d{6,7}$","Validates Croatia landline numbers +385 then 7-8 digits starting 1-5"  
Regex_croatia_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Croatia GPS coordinates decimal degrees"  
Regex_croatia_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Croatia GPS coordinates degrees/minutes N/S/E/W"  
Regex_croatia_eu_mobile_number,"^\+3859\d{7}$","Validates Croatia mobile numbers +385 then 8 digits starting 9"  
Regex_croatia_eu_passport_number,"^[A-Z]{2}\d{7}$","Validates Croatia passport number: 2 letters + 7 digits"  
Regex_croatia_eu_ssn_or_equivalent,"^\d{11}$","Validates Croatia personal ID number (OIB) 11 digits"  
Regex_croatia_eu_tax_file_number,"^\d{11}$","Validates Croatia tax file number (OIB) 11 digits"  
Regex_croatia_eu_telephone_number,"^\+385[1-5]\d{6,7}$","Validates Croatia landline numbers +385 then 7-8 digits starting 1-5"  
Regex_croatia_id_card,"^[A-Z0-9]{9}$","Validates Croatia ID card 9 alphanumeric characters"  
Regex_cyprus_eu_driver's_license_number,"(placeholder)","Validates Cyprus driver’s licence numbers"  
Regex_cyprus_eu_formatted_mobile_number,"^\+3579\d{7}$","Validates Cyprus mobile numbers +357 then 8 digits starting 9"  
Regex_cyprus_eu_formatted_telephone_number,"^\+3572\d{6}$","Validates Cyprus landline numbers +357 then 7 digits starting 2"  
Regex_cyprus_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Cyprus GPS coordinates decimal degrees"  
Regex_cyprus_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Cyprus GPS coordinates degrees/minutes N/S/E/W"  
Regex_cyprus_eu_mobile_number,"^\+3579\d{7}$","Validates Cyprus mobile numbers +357 then 8 digits starting 9"  
Regex_cyprus_eu_national_id_card,"^\d{8}$","Validates Cyprus national ID card (8 digits)"  
Regex_cyprus_eu_passport_date,"^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/\d{4}$","Validates Cyprus passport date DD/MM/YYYY"  
Regex_cyprus_eu_passport_number,"^[A-Z]{1}\d{7}$","Validates Cyprus passport number 1 letter + 7 digits"  
Regex_cyprus_eu_tax_file_number,"^\d{9}$","Validates Cyprus tax file number 9 digits"  
Regex_cyprus_eu_telephone_number,"^\+3572\d{6}$","Validates Cyprus landline numbers +357 then 7 digits starting 2"  
Regex_czech_republic_eu_driver's_license_number,"(placeholder)","Validates Czech Republic driver’s licence numbers"  
Regex_czech_republic_eu_formatted_mobile_number,"^\+420[6-7]\d{8}$","Validates Czech mobile numbers +420 then 9 digits starting 6 or 7"  
Regex_czech_republic_eu_formatted_telephone_number,"^\+420[2]\d{8}$","Validates Czech landline numbers +420 then 9 digits starting 2"  
Regex_czech_republic_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Czech Republic GPS coordinates decimal degrees"  
Regex_czech_republic_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Czech Republic GPS coordinates degrees/minutes N/S/E/W"  
Regex_czech_republic_eu_mobile_number,"^\+420[6-7]\d{8}$","Validates Czech mobile numbers +420 then 9 digits starting 6 or 7"  
Regex_czech_republic_eu_passport_number,"^[A-Z]{2}\d{7}$","Validates Czech passport number 2 letters + 7 digits"  
Regex_czech_republic_eu_ssn_or_equivalent,"^\d{10}$","Validates Czech Republic personal number (Rodné číslo) 10 digits"  
Regex_czech_republic_eu_tax_file_number,"^\d{10}$","Validates Czech Republic tax file number 10 digits"  
Regex_czech_republic_eu_telephone_number,"^\+420[2]\d{8}$","Validates Czech landline numbers +420 then 9 digits starting 2"  
Regex_denmark_eu_driver's_license_number,"(placeholder)","Validates Denmark driver’s licence numbers"  
Regex_denmark_eu_formatted_mobile_number,"^\+45[2-9]\d{7}$","Validates Denmark mobile numbers +45 then 8 digits starting 2-9"  
Regex_denmark_eu_formatted_telephone_number,"^\+45[1]\d{7}$","Validates Denmark landline numbers +45 then 8 digits starting 1"  
Regex_denmark_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Denmark GPS coordinates decimal degrees"  
Regex_denmark_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Denmark GPS coordinates degrees/minutes N/S/E/W"  
Regex_denmark_eu_mobile_number,"^\+45[2-9]\d{7}$","Validates Denmark mobile numbers +45 then 8 digits starting 2-9"  
Regex_denmark_eu_passport_number,"^[A-Z]{2}\d{7}$","Validates Denmark passport number 2 letters + 7 digits"  
Regex_denmark_eu_ssn_or_equivalent,"^\d{10}$","Validates Denmark personal ID number (CPR) 10 digits"  
Regex_denmark_eu_tax_file_number,"^\d{10}$","Validates Denmark tax file number 10 digits"  
Regex_denmark_eu_telephone_number,"^\+45[1]\d{7}$","Validates Denmark landline numbers +45 then 8 digits starting 1"  
Regex_denmark_id,"^\d{10}$","Validates Denmark national ID 10 digits"  
CEP_AzureEmulatorStorageAccountFilter,"(placeholder)","Matches Azure Storage Emulator account names for DLP/compliance"  
CEP_CommonExampleKeywords,"(placeholder)","Matches common example keywords often used in code or configs"  
CEP_PasswordPlaceHolder,"(placeholder)","Matches placeholder strings representing passwords"  
CEP_Regex_AzureConnectionString,"(placeholder)","Matches Azure connection strings"  
CEP_Regex_AzureDocumentDBAuthKey,"(placeholder)","Matches Azure DocumentDB (CosmosDB) authentication keys"  
CEP_Regex_AzureIoTConnectionString,"(placeholder)","Matches Azure IoT Hub connection strings"  
CEP_Regex_AzurePublishSettingPasswords,"(placeholder)","Matches passwords found in Azure publish settings files"  
CEP_Regex_AzureRedisCacheConnectionString,"(placeholder)","Matches Azure Redis Cache connection strings"  
CEP_Regex_AzureSAS,"(?:^|[\s,;:\(\)\[\]\"'&])(sig\s{0,2}=\s{0,2}[a-zA-Z0-9%]{43,53}%3[Dd][^a-zA-Z0-9%])(?:$|[\s,;:\(\)\[\]\"'&])","Matches Azure SAS token signatures"  
CEP_Regex_AzureServiceBusConnectionString,"(placeholder)","Matches Azure Service Bus connection strings"  
CEP_Regex_AzureStorageAccountKey,"(placeholder)","Matches Azure Storage account keys"  
CEP_Regex_AzureStorageAccountKeyGeneric,"(placeholder)","Matches generic Azure Storage account keys"  
CEP_Regex_SQLServerConnectionString,"(placeholder)","Matches SQL Server connection strings"  
Regex_argentina_national_id,"^\d{7,8}$","Validates Argentina national ID (DNI) 7-8 digits"  
Regex_australia_bank_account_number,"^\d{6,9}$","Validates Australia bank account numbers"  
Regex_australia_bank_account_number_bsb,"^\d{6}$","Validates Australian BSB codes (Bank-State-Branch) 6 digits"  
Regex_australia_drivers_license_number,"(placeholder)","Validates Australia drivers license numbers (state-specific formats)"  
Regex_australia_passport_number,"^[A-Z]\d{7}$","Validates Australia passport number 1 letter + 7 digits"  
Regex_austria_eu_driver's_license_number,"(placeholder)","Validates Austria driver’s license numbers"  
Regex_austria_eu_formatted_mobile_number,"^\+43[6]\d{7,9}$","Validates Austria mobile numbers +43 then 7-9 digits starting 6"  
Regex_austria_eu_formatted_telephone_number_1,"^\+43[1-9]\d{6,9}$","Validates Austria landline numbers +43 then 7-9 digits starting 1-9"  
Regex_austria_eu_formatted_telephone_number_2,"^\+43[1-9]\d{6,9}$","Alternative pattern for Austria landlines"  
Regex_austria_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Austria GPS coordinates decimal degrees"  
Regex_austria_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Austria GPS coordinates degrees/minutes N/S/E/W"  
Regex_austria_eu_mobile_number,"^\+43[6]\d{7,9}$","Validates Austria mobile numbers +43 then 7-9 digits starting 6"  
Regex_austria_eu_national_id_card,"^\d{9}$","Validates Austria national ID card 9 digits"  
Regex_austria_eu_passport_number,"^[A-Z]{2}\d{7}$","Validates Austria passport number: 2 letters + 7 digits"  
Regex_austria_eu_ssn_or_equivalent,"^\d{9}$","Validates Austria social security number (9 digits)"  
Regex_austria_eu_telephone_number_1,"^\+43[1-9]\d{6,9}$","Validates Austria landline numbers +43 then 7-9 digits starting 1-9"  
Regex_austria_eu_telephone_number_2,"^\+43[1-9]\d{6,9}$","Alternative pattern for Austria landlines"  
Regex_belgium_eu_driver's_license_number,"(placeholder)","Validates Belgium driver’s license numbers"  
Regex_belgium_eu_formatted_mobile_number,"^\+32[4]\d{8}$","Validates Belgium mobile numbers +32 then 9 digits starting 4"  
Regex_belgium_eu_formatted_telephone_number_1,"^\+32[1-9]\d{7,8}$","Validates Belgium landline numbers +32 then 8-9 digits starting 1-9"  
Regex_belgium_eu_formatted_telephone_number_2,"^\+32[1-9]\d{7,8}$","Alternative pattern for Belgium landlines"  
Regex_belgium_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates Belgium GPS coordinates decimal degrees"  
Regex_belgium_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates Belgium GPS coordinates degrees/minutes N/S/E/W"  
Regex_belgium_eu_mobile_number,"^\+32[4]\d{8}$","Validates Belgium mobile numbers +32 then 9 digits starting 4"  
Regex_belgium_eu_passport_number,"^[A-Z]{2}\d{7}$","Validates Belgium passport number 2 letters + 7 digits"  
Regex_belgium_eu_ssn_or_equivalent,"^\d{11}$","Validates Belgium social security number (11 digits)"  
Regex_belgium_eu_tax_file_number,"^\d{11}$","Validates Belgium tax file number (11 digits)"  
Regex_belgium_eu_telephone_number_1,"^\+32[1-9]\d{7,8}$","Validates Belgium landline numbers +32 then 8-9 digits starting 1-9"  
Regex_belgium_eu_telephone_number_2,"^\+32[1-9]\d{7,8}$","Alternative pattern for Belgium landlines"  
Regex_belgium_national_number,"^\d{11}$","Validates Belgium National Number (SSN) 11 digits"  
Regex_bulgaria_eu_driver's_license_number,"(placeholder)","Validates Bulgaria driver’s license numbers"  
Regex_bulgaria_eu_formatted_mobile_number,"^\+3598\d{7}$","Validates Bulgaria mobile numbers +359 then 8 digits starting 8"  
Regex_sweden_eu_telephone_number,"^\+46\d{9}$","Validates Sweden telephone numbers +46 then 9 digits"  
Regex_sweden_passport_number,"^[A-Z]{2}\d{7}$","Validates Sweden passport number 2 letters + 7 digits"  
Regex_swift,"^[A-Z]{6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3})?$","Validates SWIFT/BIC codes"  
Regex_taiwan_passport,"^[A-Z]\d{8}$","Validates Taiwan passport number 1 letter + 8 digits"  
Regex_taiwan_resident_certificate,"^[A-Z][12]\d{8}$","Validates Taiwan resident certificate number"  
Regex_uae_id_card_number,"^\d{15}$","Validates UAE ID card number 15 digits"  
Regex_uae_passport_number,"^[A-Z]\d{7}$","Validates UAE passport number 1 letter + 7 digits"  
Regex_uk_electoral,"^[A-Z]{2}\d{6}$","Validates UK electoral number"  
Regex_uk_eu_formatted_mobile_number,"^\+44\d{10}$","Validates UK mobile numbers +44 then 10 digits"  
Regex_uk_eu_formatted_telephone_number,"^\+44\d{10}$","Validates UK landline numbers +44 then 10 digits"  
Regex_uk_eu_gps_data_1,"^[-+]?\d{1,2}\.\d+,\s*[-+]?\d{1,3}\.\d+$","Validates UK GPS coordinates decimal degrees"  
Regex_uk_eu_gps_data_2,"^[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'\s*[NSEW]\s*\d{1,3}°\s*\d{1,2}\.\d+'$","Validates UK GPS coordinates degrees/minutes N/S/E/W"  
Regex_uk_eu_mobile_number,"^\+44\d{10}$","Validates UK mobile numbers +44 then 10 digits"  
Regex_uk_eu_tax_file_number,"^\d{10}$","Validates UK tax file number 10 digits"  
Regex_uk_eu_telephone_number,"^\+44\d{10}$","Validates UK landline numbers +44 then 10 digits"  
Regex_Ukraine_Passport_Domestic,"^\d{9}$","Validates Ukraine domestic passport number 9 digits"  
Regex_Ukraine_Passport_International,"^[A-Z]{2}\d{6}$","Validates Ukraine international passport 2 letters + 6 digits"  
Regex_usa_Bank_Account,"^\d{9,12}$","Validates USA bank account numbers 9-12 digits"  
Regex_usa_bank_account_number,"^\d{9,12}$","Validates USA bank account numbers 9-12 digits"  
CEP_AzureEmulatorStorageAccountFilter,"(placeholder)","Matches Azure Storage Emulator account names for DLP/compliance"  
CEP_CommonExampleKeywords,"(placeholder)","Matches common example keywords often used in code or configs"  
CEP_PasswordPlaceHolder,"(placeholder)","Matches placeholder strings representing passwords"  
CEP_Regex_AzureConnectionString,"(placeholder)","Matches Azure connection strings"  
CEP_Regex_AzureDocumentDBAuthKey,"(placeholder)","Matches Azure DocumentDB (CosmosDB) authentication keys"  
CEP_Regex_AzureIoTConnectionString,"(placeholder)","Matches Azure IoT Hub connection strings"  
CEP_Regex_AzurePublishSettingPasswords,"(placeholder)","Matches passwords found in Azure publish settings files"  
CEP_Regex_AzureRedisCacheConnectionString,"(placeholder)","Matches Azure Redis Cache connection strings"  
CEP_Regex_AzureSAS,"(?:^|[\s,;:\(\)\[\]\"'&])(sig\s{0,2}=\s{0,2}[a-zA-Z0-9%]{43,53}%3[Dd][^a-zA-Z0-9%])(?:$|[\s,;:\(\)\[\]\"'&])","Matches Azure SAS token signatures"  
CEP_Regex_AzureServiceBusConnectionString,"(placeholder)","Matches Azure Service Bus connection strings"  
CEP_Regex_AzureStorageAccountKey,"(placeholder)","Matches Azure Storage account keys"  
CEP_Regex_AzureStorageAccountKeyGeneric,"(placeholder)","Matches generic Azure Storage account keys"  
CEP_Regex_SQLServerConnectionString,"(placeholder)","Matches SQL Server connection strings"  
Regex_poland_eu_mobile_number,"^\+48\d{9}$","Validates Poland mobile numbers +48 then 9 digits"  
Regex_south_korea_passport_number,"^[A-Z0-9]{8,9}$","Validates South Korea passport number 8-9 alphanumeric"  
Regex_spain_eu_formatted_mobile_number,"^\+34\d{9}$","Validates Spain mobile numbers +34 then 9 digits"  
Regex_romania_eu_driver's_license_number,"(placeholder)","Validates Romania driver’s license numbers"  
Regex_lithuania_eu_driver's_license_number,"(placeholder)","Validates Lithuania driver’s license numbers"  
Regex_philippines_passport_number,"(placeholder)","Validates Philippines passport numbers"  
Regex_philippines_unified_id,"(placeholder)","Validates Philippines Unified ID"  
Regex_phillipines_national_id,"(placeholder)","Validates Philippines national ID"  
Regex_ipv4_address,"^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$","Validates IPv4 addresses"  
Regex_ipv6_address,"^([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$","Validates IPv6 addresses"  
Regex_dummy_no_match_number,"^$","Dummy regex that matches nothing"  
Regex_Ecuador_Unique_Identification_Number,"(placeholder)","Validates Ecuador unique ID numbers"  
Regex_estonia_eu_driver's_license_number,"(placeholder)","Validates Estonia driver’s license numbers"  
Regex_estonia_eu_formatted_mobile_number,"(placeholder)","Validates Estonia mobile numbers"  
Regex_estonia_eu_formatted_telephone_number,"(placeholder)","Validates Estonia telephone numbers"  
Regex_estonia_eu_gps_data_1,"(placeholder)","Validates Estonia GPS data format 1"  
Regex_estonia_eu_gps_data_2,"(placeholder)","Validates Estonia GPS data format 2"  
Regex_estonia_eu_mobile_number,"(placeholder)","Validates Estonia mobile numbers"  
Regex_estonia_eu_national_id_card,"(placeholder)","Validates Estonia national ID card"  
Regex_estonia_eu_passport_number,"(placeholder)","Validates Estonia passport number"  
Regex_estonia_eu_tax_file_number,"(placeholder)","Validates Estonia tax file number"  
Regex_estonia_eu_telephone_number,"(placeholder)","Validates Estonia telephone numbers"  
Regex_eu_passport_date1,"(placeholder)","Validates EU passport date format 1"  
Regex_eu_passport_date2,"(placeholder)","Validates EU passport date format 2"  
Regex_eu_passport_date3,"(placeholder)","Validates EU passport date format 3"  
Regex_Filter_TrivialValue2_20601768_CEP2.0,"(placeholder)","Matches trivial value filter"  
Regex_finland_eu_driver's_license_number,"(placeholder)","Validates Finland driver’s license numbers"  
Regex_finland_eu_formatted_mobile_number,"(placeholder)","Validates Finland mobile numbers"  
Regex_finland_eu_formatted_telephone_number,"(placeholder)","Validates Finland telephone numbers"  
Regex_finland_eu_gps_data_1,"(placeholder)","Validates Finland GPS data 1"  
Regex_finland_eu_gps_data_2,"(placeholder)","Validates Finland GPS data 2"  
Regex_finland_eu_mobile_number,"(placeholder)","Validates Finland mobile numbers"  
Regex_finland_eu_ssn_or_equivalent,"(placeholder)","Validates Finland SSN or equivalent"  
Regex_finland_eu_tax_file_number,"(placeholder)","Validates Finland tax file number"  
Regex_finland_eu_telephone_number,"(placeholder)","Validates Finland telephone numbers"  
Regex_Finland_European_Health_Insurance_Number,"(placeholder)","Validates Finland European Health Insurance number"  
Regex_finland_passport_number,"(placeholder)","Validates Finland passport number"  
Regex_france_cni,"(placeholder)","Validates France national identity card"  
Regex_france_eu_formatted_mobile_number,"(placeholder)","Validates France mobile numbers"  
Regex_france_eu_formatted_telephone_number,"(placeholder)","Validates France telephone numbers"  
Regex_france_eu_gps_data_1,"(placeholder)","Validates France GPS data 1"  
Regex_france_eu_gps_data_2,"(placeholder)","Validates France GPS data 2"  
Regex_france_eu_mobile_number,"(placeholder)","Validates France mobile numbers"  
Regex_france_eu_tax_file_number,"(placeholder)","Validates France tax file number"  
Regex_france_eu_telephone_number,"(placeholder)","Validates France telephone numbers"  
Regex_France_Health_Insurance_Number,"(placeholder)","Validates France Health Insurance number"  
Regex_germany_eu_formatted_mobile_number,"(placeholder)","Validates Germany mobile numbers"  
Regex_germany_eu_formatted_telephone_number,"(placeholder)","Validates Germany telephone numbers"  
Regex_germany_eu_gps_data_1,"(placeholder)","Validates Germany GPS data 1"  
Regex_germany_eu_gps_data_2,"(placeholder)","Validates Germany GPS data 2"  
Regex_germany_eu_mobile_number,"(placeholder)","Validates Germany mobile numbers"  
Regex_germany_eu_tax_file_number,"(placeholder)","Validates Germany tax file number"  
Regex_germany_eu_telephone_number,"(placeholder)","Validates Germany telephone numbers"  
Regex_germany_id_card,"(placeholder)","Validates Germany ID card"  
Regex_greece_eu_driver's_license_number,"(placeholder)","Validates Greece driver’s license numbers"  
Regex_greece_eu_formatted_mobile_number,"(placeholder)","Validates Greece mobile numbers"  
Regex_greece_eu_formatted_telephone_number,"(placeholder)","Validates Greece telephone numbers"  
Regex_greece_eu_gps_data_1,"(placeholder)","Validates Greece GPS data 1"  
Regex_greece_eu_gps_data_2,"(placeholder)","Validates Greece GPS data 2"  
Regex_greece_eu_mobile_number,"(placeholder)","Validates Greece mobile numbers"  
Regex_greece_eu_passport_date,"(placeholder)","Validates Greece passport date"  
Regex_greece_eu_passport_number,"(placeholder)","Validates Greece passport number"  
Regex_greece_eu_tax_file_number,"(placeholder)","Validates Greece tax file number"  
Regex_greece_eu_telephone_number,"(placeholder)","Validates Greece telephone numbers"  
Regex_greece_id_card,"(placeholder)","Validates Greece ID card"  
