# write_mx_excel_direct.py
from openpyxl import Workbook

rows = [
["MXRecord","location","type","Sub_Type","Org","Notes"],
["mail.protection.outlook.com","Cloud","Email Security","Spam filtering, malware filtering, routing","Microsoft 365","Default MX for Exchange Online Protection"],
["gslb.pphosted.com","Cloud","Email Security","Spam filtering, malware protection","Proofpoint","Proofpoint Protection Service MX"],
["ess.barracudanetworks.com","Cloud","Email Security","Spam filtering, malware filtering","Barracuda Networks","Barracuda ESS hosted filtering"],
["aspmx.l.google.com","Cloud","Email","Routing","Google Workspace","Primary Google MX"],
["in.tmes-anz.trendmicro.com","Cloud","Email Security","Threat filtering","Trend Micro","Hosted Trend Micro Email Security (ANZ region)"],
["mail.eo.outlook.com","Cloud","Email","Routing","Microsoft 365","Exchange Online Front-End MX"],
["l.google.com","Cloud","Email","Routing","Google Workspace","Google routing node"],
["googlemail.com","Cloud","Email","Routing","Google Workspace","Historic Google MX domain"],
["a.ess.au.barracudanetworks.com","Cloud","Email Security","Spam filtering","Barracuda Networks","Barracuda Australian cluster"],
["pphosted.com","Cloud","Email Security","Spam/Malware filtering","Proofpoint","Proofpoint hosted MX"],
["b.ess.au.barracudanetworks.com","Cloud","Email Security","Filtering","Barracuda Networks","Barracuda Australian cluster B"],
["com.1.0001.arsmtp.com","Cloud","Email Security","Filtering, routing","MailChannels/ARSmtp","Anti-spam mail relay"],
["pamx1.hotmail.com","Cloud","Email","Routing","Microsoft/Outlook.com","Legacy Outlook/Hotmail MX"],
["mx1.arsmtp.com","Cloud","Email Security","Filtering","MailChannels/ARSmtp","MailChannels anti-spam MX"],
["mimecast.com","Cloud","Email Security","Filtering, archiving","Mimecast","Main Mimecast MX"],
["p10.mxthunder.com","Cloud","Email Security","Spam filtering","MXThunder/Email Laundry","MX filtering platform"],
["mailfilter.net.au","Cloud","Email Security","Filtering","MailFilter Australia","Hosted filtering"],
["ppe-hosted.com","Cloud","Email Security","Proofpoint Essentials","Proofpoint","Proofpoint Essentials MX"],
["msv1.invalid","Cloud","Email","Verification","Microsoft","Test/verification MX for domain validation"],
["p20.mxthunder.net","Cloud","Email Security","Filtering","MXThunder","Anti-spam relay cluster"],
["mtaroutes.com","Cloud","Email Security","Routing","MailChannels/ARSmtp","Mail routing provider"],
["com.au.inbound.anz.mpmailmx.com","Cloud","Email Security","Filtering","MPMailMX / Inbound APAC","Inbound filtering for AU/NZ"],
["com.2.0001.arsmtp.com","Cloud","Email Security","Security relay","MailChannels/ARSmtp","Secure email relay"],
["hosting-cloud.net","Cloud","Email Hosting","Email hosting","Hosting Cloud","Service provider mail cluster"],
["in.tmes.trendmicro.com","Cloud","Email Security","Filtering","Trend Micro","Trend Micro Email Security global"],
["firstcloudsecurity.net","Cloud","Email Security","Filtering","FirstCloudSecurity","Hosted anti-spam"],
["mx2.arsmtp.com","Cloud","Email Security","Filtering","MailChannels","Secondary ARSMTP node"],
["netregistry.net","Cloud","Email Hosting","Email hosting","Netregistry / Webcentral","Australian hosting"],
["p30.mxthunder.net","Cloud","Email Security","Filtering","MXThunder","Anti-spam cluster"],
["mail.protection.office365.us","Cloud","Email Security","Filtering, routing","Microsoft (US)","US Sovereign Cloud MX"],
["mx.av-mx.com","Cloud","Email Security","Filtering","AV-MX","Hosted anti-spam MX"],
["com.au.inbound.anz.mpmailmx.net","Cloud","Email Security","Filtering","MPMailMX APAC","Alternative inbound node"],
["carrierzone.com","Cloud","Email Hosting","Hosting","CarriersZone","Generic hosting MX"],
["netsol.xion.oxcs.net","Cloud","Email","Mail relay","Network Solutions / Web.com","Hosted mail routing"],
["google.com","Cloud","Email","Routing","Google","Google mail systems"],
["titanhq.com","Cloud","Email Security","Filtering","TitanHQ (SpamTitan)","Hosted email security platform"],
["us.messagelabs.com","Cloud","Email Security","Filtering, ATP","Symantec/Broadcom MessageLabs","Enterprise email security"],
["mail-forwarder.io","Cloud","Email","Routing","MailForwarder.io","Mail routing service"],
["p40.mxthunder.net","Cloud","Email Security","Filtering","MXThunder","Node p40"],
["in.mailcontrol.com","Cloud","Email Security","Filtering","MailControl / Forcepoint","Hosted email security"],
["inbound.emailservice.io","Cloud","Email Hosting","Inbound routing","EmailService.io","Mail hosting platform"],
["email-hosting.net.au","Cloud","Email Hosting","Hosting","AU Email Hosting","Australian email hosting provider"],
["a.ess.uk.barracudanetworks.com","Cloud","Email Security","Filtering","Barracuda Networks","UK cluster A"],
["hornetsecurity.com","Cloud","Email Security","Filtering, DLP","HornetSecurity","Full email security suite"],
["bne.server-mail.com","Cloud","Email Hosting","Hosting","Server-Mail (AU)","Brisbane mail cluster"],
["fortimailcloud.com","Cloud","Email Security","Filtering","Fortinet FortiMailCloud","SaaS email security"],
["prod.hydra.sophos.com","Cloud","Email Security","Sophos Email","Sophos","Sophos Hydra mail cluster"],
["email-protect.gosecure.net","Cloud","Email Security","Filtering","GoSecure","Email protection service"],
["21.ik2.com","Cloud","Email Hosting","Hosting","IK2","Generic mail hosting"],
["ax.email","Cloud","Email Hosting","Routing","ax.email","Transactional email provider"],
["partnerconsole.net","Cloud","Email Hosting","Hosting","TPP Wholesale","AU hosting mail nodes"],
["mxrouting.net","Cloud","Email Hosting","Email hosting","MxRoute","Email host for SMB"],
["emailsrvr.com","Cloud","Email Hosting","Hosting / MX","Rackspace Email","Rackspace mail cluster"],
["p10.spamhero.com","Cloud","Email Security","Filtering","SpamHero","Spam filtering node p10"],
["com.1.arsmtp.com","Cloud","Email Security","Filtering","MailChannels","ARSmtp routing"],
["syd1.stableserver.net","Cloud","Email Hosting","Hosting","StableHost AU","Sydney mail cluster"],
["zoho.com","Cloud","Email Hosting","Email hosting","Zoho","Zoho Mail MX"],
["in.tmes.trendmicro.eu","Cloud","Email Security","Filtering","Trend Micro EU","European cluster"],
["gslb.gpphosted.com","Cloud","Email Security","Spam/malware filtering","Proofpoint","Alternative Proofpoint MX"],
["telstra.net","Cloud","Email Hosting","Carrier mail","Telstra Australia","MX for Telstra customers"],
["doteasy.com","Cloud","Email Hosting","Hosting","Doteasy","Shared hosting provider"],
["mx.mailhop.org","Cloud","Email Routing","Dynamic DNS routing","MailHop","Mail relay / smarthost"],
["b.ess.uk.barracudanetworks.com","Cloud","Email Security","Filtering","Barracuda Networks","UK cluster B"],
["secureserver.net","Cloud","Email Hosting","Inbound mail","GoDaddy","GoDaddy hosting mail MX"],
["pair.com","Cloud","Email Hosting","Hosting","Pair Networks","US hosting mail"],
["inbound.emailservice.cc","Cloud","Email Hosting","Inbound routing","EmailService.cc","Inbound routing host"],
["nameserver.net.au","Cloud","Email Hosting","Hosting","AU hosting provider",""],
["fortimail.com","Cloud","Email Security","Filtering","Fortinet","FortiMail on-prem/cloud hybrid"],
["melbourneit.net","Cloud","Email Hosting","Hosting","MelbourneIT / Arq Group","AU hosting"],
["org.1.0001.arsmtp.com","Cloud","Email Security","Filtering","MailChannels","ARSmtp relay"],
["mailgun.org","Cloud","Email","Transactional Email","Mailgun","Transactional email service"],
["kasserver.com","Cloud","Email Hosting","Hosting","Kasserver / All-Inkl","German hosting"],
["p30.spamhero.net","Cloud","Email Security","Filtering","SpamHero","Node p30"],
["p20.spamhero.net","Cloud","Email Security","Filtering","SpamHero","Node p20"],
["us.email.fireeyecloud.com","Cloud","Email Security","Advanced threat detection","FireEye / Trellix","Email anti-phishing"],
["antispam.mailspamprotection.com","Cloud","Email Security","Spam filtering","SpamExperts","SaaS filtering"],
["org.2.0001.arsmtp.com","Cloud","Email Security","Filtering","MailChannels","Secure relay"],
["22.ik2.io","Cloud","Email Hosting","Hosting","IK2","Mail hosting"],
["spamtitan.com","Cloud","Email Security","Filtering","TitanHQ","SpamTitan MX"],
["zoho.com.au","Cloud","Email Hosting","Email hosting","Zoho AU","Regional Zoho MX"],
["inbound.emailservice.co","Cloud","Email Hosting","Inbound routing","EmailService.co",""],
["p40.spamhero.net","Cloud","Email Security","Filtering","SpamHero","Node p40"],
["antispamcloud.com","Cloud","Email Security","Filtering","SpamExperts","Hosted spam protection"],
["secureintellicentre.net.au","Cloud","Email Security","Security routing","Macquarie Cloud Services","Secure email routing"],
["relay1g.spamh.com","Cloud","Email Security","Filtering","Spamh.com","Spam filtering"],
["mx-verification.google.com","Cloud","Email","Verification","Google","Used for domain verification"],
["hes.trendmicro.com","Cloud","Email Security","Filtering","Trend Micro HES","Hosted Email Security"],
["eu.messagelabs.com","Cloud","Email Security","Filtering","Symantec/Broadcom MessageLabs","Enterprise email security EU"],
["megamailservers.com","Cloud","Email Hosting","Hosting","MegaMailServers","Mail hosting"],
["us.scanscope.net","Cloud","Email Security","Filtering","ScanScope","Security relay"],
["mailcluster.com.au","Cloud","Email Hosting","Hosting","MailCluster AU","Mail hosting"],
["webworx.net.au","Cloud","Email Hosting","Hosting","Webworx AU","Hosting provider"],
["mail.ovh.net","Cloud","Email Hosting","Email hosting","OVHcloud","Primary MX for OVH"],
["mx1-us.mailanyone.net","Cloud","Email Security","Filtering","Mailanyone / Securence","US region"],
["mx.cloudflare.net","Cloud","Email Routing","Routing/Proxy","Cloudflare","Cloudflare Email Routing"],
["antispameurope.com","Cloud","Email Security","Filtering","HornetSecurity/Antispam Europe","European anti-spam service"],
["newtekwebhosting.com","Cloud","Email Hosting","Hosting","NewTek Hosting","Hosting provider"],
["megamailservers.eu","Cloud","Email Hosting","Hosting","MegaMailServers EU","Mail hosting EU"],
["sge.net","Cloud","Email Hosting","Hosting","SGE Networks","Hosting"],
["mx1.mailanyone.net","Cloud","Email Security","Filtering","Mailanyone / Securence","Primary MX"],
["internetmailserver.net","Cloud","Email Hosting","Hosting","InternetMailServer.net","Mail hosting"],
["in.tmes-sg.trendmicro.com","Cloud","Email Security","Filtering","Trend Micro SG","SG region TES"],
["mxroute.com","Cloud","Email Hosting","Email hosting","MxRoute","Direct MX servers"],
["mx2.mx25.net","Cloud","Email Security","Filtering","mx25 / Reflexion","Anti-spam provider"],
["jellyfish.systems","Cloud","Email Hosting	Routing","Jellyfish Systems","Mail routing"],
["msv1.invalid.outlook.com","Cloud","Email","Verification","Microsoft","DNS validation token alias"],
["accountservergroup.com","Cloud","Email Hosting","Hosting","AccountServerGroup","Hosting"],
["acecommunications.com.au","Cloud","Email Hosting","Hosting","Ace Communications AU","AU hosting"],
["pub.mailpod12-cph3.one.com","Cloud","Email Hosting","Hosting","ONE.com","EU hosting cluster"],
["mailspamprotection.com","Cloud","Email Security","Filtering","SpamExperts","Hosted filtering"],
["everyone.net","Cloud","Email Hosting","Email hosting","Everyone.net / Synacor","Mail hosting"],
["junkemailfilter.com","Cloud","Email Security","Filtering","JunkEmailFilter.com","Anti-spam filtering provider"],
["com.snwlhosted.com","Cloud","Email Security","Filtering","SonicWall Hosted Email Security","SonicWall hosted"],
["emailsecurity.app","Cloud","Email Security","Filtering","EmailSecurity.app","Hosted email security"],
["hosting-servers.com.au","Cloud","Email Hosting","Hosting","Hosting Servers AU","Hosting"],
["fluccs.net.au","Cloud","Email Hosting","Hosting","Fluccs AU","Hosting"],
["relay1i.spamh.com","Cloud","Email Security","Filtering","Spamh.com","Spam filtering"],
["ovh.net","Cloud","Email Hosting","Email hosting","OVHcloud",""],
["mx62.com","Cloud","Email Hosting","Hosting","mx62","Mail host"],
["mxrecord.io","Cloud","Email Tools","Lookup service","mxrecord.io","Used for MX diagnostics"]
]

from openpyxl import Workbook
wb = Workbook()
ws = wb.active
ws.title = "MX Records"
for r in rows:
    ws.append(r)
wb.save("mx_records_full.xlsx")
print("Saved mx_records_full.xlsx")
